Added more headings font-weight options, #379
cagov/design-system pull request #795
Opened 2022-04-13 18:54 UTC by kkoryaka

- Added more Public Sans font files to the fonts folder (font weight variations)
- Added references to those additional fonts files in _fonts.scss
- Added sample page with real time content that is displaying headings and their font-weight variations

Figma headings font exploration reference screenshot:
![Screen Shot 2022-04-13 at 11 47 31 AM](https://user-images.githubusercontent.com/31669748/163250397-ed3177a1-9587-4cb2-9cda-7fd9e2d44dc1.png)

2022-04-13 19:42 UTC, aaronhans commented
Nice @kkoryaka! Will be cool to split this out into a separate typography component soon

2022-04-13 22:05 UTC, kmbrlygl requested changes
One suggested style addition to h5. Thanks!

2022-04-13 22:46 UTC, kkoryaka commented on docs/pages/typography.md
> +h5 {font-weight:  var(--font-weight-8, 800);}
@kmbrlygl  Just added it in my latest commit

2022-04-13 22:52 UTC, kmbrlygl approved these changes
Looks great! Thanks Konstantin

2022-04-13 22:58 UTC, merged

2022-04-21 23:49 UTC, yesenia-gtz commented
Good to go @timothyshambra, Thank you!